version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - ./raissa.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flask:
    image: raissaglaucie34/twoge:raissa
    container_name: flask
    ports:
      - "8080:8080"
    env_file:
      - ./raissa.env
    depends_on:
      - postgres
    command: ["sh", "-c", "sleep 5 && python app.py"]

volumes:
  postgres_data:
