apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1

nodeGroups:
  - name: amd64-node-group
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 80