apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: flask-app
type: Opaque
stringData:
  # Flask app environment
  DB_USER: dXNlcg== # "user" in base64
  DB_PASSWORD: cGFzcw== # "pass" in base64
  # Postgres environment
  POSTGRES_USER:  dXNlcg== # "user" in base64
  POSTGRES_PASSWORD: cGFzcw== # "pass" in base64